sonar.projectKey=Domingax_lekto
sonar.organization=domingax
sonar.host.url=https://sonarcloud.io

sonar.projectName=Lekto
sonar.sourceEncoding=UTF-8

sonar.sources=core/src/commonMain/kotlin,core/src/jvmMain/kotlin,app/src/commonMain/kotlin,app/src/desktopMain/kotlin,app/src/androidMain/kotlin,integrations/webdav/src/commonMain/kotlin

sonar.tests=core/src/commonTest/kotlin,core/src/jvmTest/kotlin,app/src/desktopTest/kotlin,integrations/webdav/src/jvmTest/kotlin

sonar.exclusions=**/build/**,**/*.gradle.kts

sonar.coverage.jacoco.xmlReportPaths=build/reports/kover/report.xml

sonar.coverage.exclusions=app/src/androidMain/**,**/*.gradle.kts

sonar.kotlin.detekt.reportPaths=core/build/reports/detekt/*.xml,app/build/reports/detekt/*.xml,integrations/webdav/build/reports/detekt/*.xml

sonar.kotlin.ktlint.reportPaths=core/build/reports/ktlint/*/*.xml,app/build/reports/ktlint/*/*.xml,integrations/webdav/build/reports/ktlint/*/*.xml

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
