export { filesystemAdapter, setFilesystemRoot } from './filesystem'
export { ttsAdapter } from './tts'
export { secureStorageAdapter } from './secure-storage'
export { filePickerAdapter } from './file-picker'
export { inAppBrowserAdapter } from './in-app-browser'
export { preferencesAdapter } from './preferences'

export type { FilesystemAdapter } from './filesystem'
export type { TtsAdapter } from './tts'
export type { SecureStorageAdapter } from './secure-storage'
export type { FilePickerAdapter, PickedFile } from './file-picker'
export type { InAppBrowserAdapter } from './in-app-browser'
export type { PreferencesAdapter } from './preferences'
